---
development:
  cloud_name: dxzy39s8n
  api_key: '825465333268358'
  api_secret: hT2FIvLvR6HuKxOt9RFwXDrWFkQ
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dxzy39s8n
  api_key: '825465333268358'
  api_secret: hT2FIvLvR6HuKxOt9RFwXDrWFkQ
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dxzy39s8n
  api_key: '825465333268358'
  api_secret: hT2FIvLvR6HuKxOt9RFwXDrWFkQ
  enhance_image_tag: true
  static_image_support: false
